"""Excel 출력, CLI 배치 (요구사항서 10.3·10.4).

    export_report()      여덟 장짜리 통합문서를 ``output\\`` 에 저장
    run_batch()          YAML 케이스를 순차 실행

저장 직전 tz 를 해제하고, 파일명에 날짜·시각 접미사를 붙인다.
"""

from kwise.report.batch import (
    BatchConfig,
    BatchResult,
    CaseSpec,
    CaseSummary,
    load_batch_config,
    run_batch,
    run_case,
    summary_frame,
)
from kwise.report.columns import COLUMN_LABELS, column_label, localize
from kwise.report.document import (
    CHAPTER_COMPARISON,
    CHAPTER_DIAGNOSIS,
    CHAPTER_MEASURES,
    CHAPTER_SCOPE,
    CHAPTER_SUMMARY,
    DOCUMENT_TITLE,
    DocumentSections,
    MeasureEntry,
    build_document,
    document_bytes,
    document_path,
    export_document,
    measure_entries,
)
from kwise.report.excel import (
    DEFAULT_OUTPUT_DIR,
    NO_PV_SENSITIVITY_NOTE,
    SHEET_ORDER,
    ReportSections,
    ReportWriteError,
    build_sheets,
    export_report,
    measure_summary_frame,
    no_pv_sensitivity_frame,
    result_path,
    strip_timezone,
    write_workbook,
)
from kwise.report.frames import (
    band_frame,
    combination_frame,
    hourly_profile_frame,
    monthly_peak_frame,
    sensitivity_frame,
    solar_curve_frame,
    top_hour_frame,
)
from kwise.report.notices import (
    CONTRACT_CHANGE_WARNING,
    DATA_SOURCES,
    KNOWN_LIMITS,
    NOT_INCLUDED_NOTICE,
    UNPRICED_REASONS,
    format_won,
)
from kwise.report.standalone import (
    SIMPLE_SUM_LABEL,
    SIMPLE_SUM_NOTE,
    StandaloneRow,
    combinable_keys,
    simple_sum_won,
    standalone_frame,
    standalone_rows,
)

__all__ = [
    "CHAPTER_COMPARISON",
    "CHAPTER_DIAGNOSIS",
    "CHAPTER_MEASURES",
    "CHAPTER_SCOPE",
    "CHAPTER_SUMMARY",
    "COLUMN_LABELS",
    "CONTRACT_CHANGE_WARNING",
    "DATA_SOURCES",
    "DEFAULT_OUTPUT_DIR",
    "DOCUMENT_TITLE",
    "KNOWN_LIMITS",
    "NOT_INCLUDED_NOTICE",
    "NO_PV_SENSITIVITY_NOTE",
    "SHEET_ORDER",
    "SIMPLE_SUM_LABEL",
    "SIMPLE_SUM_NOTE",
    "UNPRICED_REASONS",
    "BatchConfig",
    "BatchResult",
    "CaseSpec",
    "CaseSummary",
    "DocumentSections",
    "MeasureEntry",
    "ReportSections",
    "ReportWriteError",
    "StandaloneRow",
    "band_frame",
    "build_document",
    "build_sheets",
    "column_label",
    "combinable_keys",
    "combination_frame",
    "document_bytes",
    "document_path",
    "export_document",
    "export_report",
    "format_won",
    "hourly_profile_frame",
    "load_batch_config",
    "localize",
    "measure_entries",
    "measure_summary_frame",
    "monthly_peak_frame",
    "no_pv_sensitivity_frame",
    "result_path",
    "run_batch",
    "run_case",
    "sensitivity_frame",
    "simple_sum_won",
    "solar_curve_frame",
    "solar_curve_sheet",
    "standalone_frame",
    "standalone_rows",
    "strip_timezone",
    "summary_frame",
    "top_hour_frame",
    "write_workbook",
]
