"""요금 엔진, 시간대 분류 (요구사항서 5장·부록 A).

    load_tariff()        요금 데이터 읽기. 단가는 절대 하드코딩하지 않는다
    validate_tariff()    부록 A.2 의 구조적 검증 (수기 입력 오타 검출)
    build_calendar()     공휴일 달력. 일요일도 공휴일로 계량한다
    classify_slots()     계절·시간대·요일 분류. 귀속은 구간 시작 시각 기준
    calculate_bill()     기본요금 + 전력량요금

모두 순수 함수다. Streamlit 을 import 하지 않는다.
"""

from kwise.tariff.demand import (
    apply_contract_floor,
    billing_demands,
    default_contract_floor_ratio,
    default_demand_bands,
    default_demand_months,
    demand_eligible_mask,
    floor_bound_months,
    is_demand_month,
    monthly_demand_basis,
    round_kw,
)
from kwise.tariff.engine import (
    AMI_BASIS_NOTICE,
    MISSING_LIMIT_RATIO,
    NOT_INCLUDED_NOTICE,
    TENTATIVE_BASE_FEE_BASIS_WARNING,
    AnnualEstimate,
    BillingOptions,
    BillingResult,
    PartialMonthPolicy,
    calculate_bill,
    demand_window_months,
)
from kwise.tariff.excess import (
    ExcessCharge,
    ExcessMonth,
    excess_charges,
    excess_grace_months,
    excess_multiplier,
    excess_tiers,
)
from kwise.tariff.holiday import (
    DEFAULT_COUNTRY,
    HolidayCalendar,
    build_calendar,
)
from kwise.tariff.labels import (
    OPTION_LABELS,
    OPTION_ORDER,
    contract_label,
    option_label,
    option_sort_key,
    selection_label,
    voltage_label,
)
from kwise.tariff.pending import (
    pending_option_notices,
)
from kwise.tariff.power_factor import (
    PowerFactorCharge,
    adjustment_per_percent,
    day_window,
    deemed_lagging_pct,
    deemed_leading_pct,
    lagging_adjustment_ratio,
    lagging_floor_pct,
    lagging_rebate_cap_pct,
    lagging_standard_pct,
    leading_adjustment_ratio,
    leading_floor_pct,
    leading_lagging_deemed_pct,
    leading_standard_pct,
    power_factor_charge,
)
from kwise.tariff.schema import (
    BANDS,
    DEFAULT_REGION_GROUP,
    ContractType,
    DayRules,
    EnergyRates,
    OptionRates,
    SpecialRule,
    TariffDataError,
    TariffSelection,
    TariffTable,
    TransitionRule,
    VoltageRates,
    available_tariff_files,
    default_tariff_dir,
    list_contract_types,
    list_options,
    list_selections,
    list_voltages,
    load_tariff,
    parse_tariff,
    switchable_selections,
)
from kwise.tariff.tou import Band, DayType, classify_slots
from kwise.tariff.validate import (
    DEFAULT_POLICY,
    DEFAULT_UNIFORM_TOLERANCE,
    OptionPairPolicy,
    ValidationFinding,
    option_pair_diffs,
    validate_tariff,
)

__all__ = [
    "AMI_BASIS_NOTICE",
    "BANDS",
    "DEFAULT_COUNTRY",
    "DEFAULT_POLICY",
    "DEFAULT_REGION_GROUP",
    "DEFAULT_UNIFORM_TOLERANCE",
    "MISSING_LIMIT_RATIO",
    "NOT_INCLUDED_NOTICE",
    "OPTION_LABELS",
    "OPTION_ORDER",
    "TENTATIVE_BASE_FEE_BASIS_WARNING",
    "AnnualEstimate",
    "Band",
    "BillingOptions",
    "BillingResult",
    "ContractType",
    "DayRules",
    "DayType",
    "EnergyRates",
    "ExcessCharge",
    "ExcessMonth",
    "HolidayCalendar",
    "OptionPairPolicy",
    "OptionRates",
    "PartialMonthPolicy",
    "PowerFactorCharge",
    "SpecialRule",
    "TariffDataError",
    "TariffSelection",
    "TariffTable",
    "TransitionRule",
    "ValidationFinding",
    "VoltageRates",
    "adjustment_per_percent",
    "apply_contract_floor",
    "available_tariff_files",
    "billing_demands",
    "build_calendar",
    "calculate_bill",
    "classify_slots",
    "contract_label",
    "day_window",
    "deemed_lagging_pct",
    "deemed_leading_pct",
    "default_contract_floor_ratio",
    "default_demand_bands",
    "default_demand_months",
    "default_tariff_dir",
    "demand_eligible_mask",
    "demand_window_months",
    "excess_charges",
    "excess_grace_months",
    "excess_multiplier",
    "excess_tiers",
    "floor_bound_months",
    "is_demand_month",
    "lagging_adjustment_ratio",
    "lagging_floor_pct",
    "lagging_rebate_cap_pct",
    "lagging_standard_pct",
    "leading_adjustment_ratio",
    "leading_floor_pct",
    "leading_lagging_deemed_pct",
    "leading_standard_pct",
    "list_contract_types",
    "list_options",
    "list_selections",
    "list_voltages",
    "load_tariff",
    "monthly_demand_basis",
    "option_label",
    "option_pair_diffs",
    "option_sort_key",
    "parse_tariff",
    "pending_option_notices",
    "power_factor_charge",
    "round_kw",
    "selection_label",
    "switchable_selections",
    "validate_tariff",
    "voltage_label",
]
