"""개선 수단 평가 (요구사항서 7장). **7장 번호 순(7.1~7.7)이다.**

    evaluate_tariff_switch()        7.1 선택요금 전환
    evaluate_contract_adjustment()  7.2 계약전력 조정
    evaluate_demand_response()      7.3 경제성DR 참여
    evaluate_power_factor()         7.4 역률 개선
    solar_curve()                   7.5 태양광 용량 곡선
    evaluate_ess()                  7.6 ESS 목표 피크 역산

**7.7 잉여 활용은 41세션에 개선안에서 빠졌다.** 잉여는 태양광을 얼마나 크게
지을지에 따라 나오는 결과이지 따로 고르는 수단이 아니다 —
:func:`~kwise.measures.surplus.evaluate_surplus` 는 그대로 남아 태양광 카드가
부른다.

**모두 독립 평가다** (14세션 2절). 기준선은 언제나 현행 요금제·현행 사용량이며,
한 수단의 결과가 다른 수단의 입력이 되지 않는다. 상호작용은
:mod:`kwise.compare` 의 조합 재계산에서만 다룬다.

절감액은 언제나 재계산이다. 수단을 적용한 15분 부하를 만들어
:func:`kwise.tariff.calculate_bill` 을 다시 부른다. 그 부하를 만드는 일은
:func:`apply_generation`·:func:`with_load` 가 맡는다.
"""

from kwise.measures.arbitrage import (
    ArbitrageValue,
    SeasonSpread,
    arbitrage_value,
    c_rate,
    default_cycles_per_day,
    peak_days_by_season,
)
from kwise.measures.base import (
    AREA_EXCEEDED,
    CAPACITY_MARKS,
    LARGEST_SAVING,
    MARGIN_SHORT,
    RECOMMENDED,
    SELECTED_CAPACITY,
    SHORTEST_PAYBACK,
    SPEC_MARKS,
    SURPLUS_HEAVY,
    SURPLUS_ONSET,
    TARGET_MISSED,
    TIED_PAYBACK,
    Certainty,
    Mark,
    annualize,
    lowest_certainty,
    mark_meaning,
    payback_years,
    spec_mark_meaning,
    spec_mark_note,
)
from kwise.measures.catalog import (
    MEASURE_CATALOG,
    TIER_INVESTMENT,
    TIER_LOW,
    TIER_NONE,
    AppliedMeasure,
    MeasureKind,
    measure_kind,
    measure_numbers,
)
from kwise.measures.contract import (
    MARGIN_NOTICE,
    NO_SAVING,
    ContractAdjustment,
    ContractStatus,
    evaluate_contract_adjustment,
)
from kwise.measures.demand_response import (
    DR_ADVISORY,
    DemandResponseResult,
    evaluate_demand_response,
    shortfall_penalty_won,
)
from kwise.measures.ess import (
    BELOW_MINIMUM_CONCLUSION,
    NOT_VIABLE_CONCLUSION,
    SPEC_TABLE_ROWS,
    DispatchResult,
    EssOptimum,
    EssOptimumPoint,
    EssResult,
    EssTargetCurve,
    EssTargetPoint,
    PeakExcess,
    analyze_peak_excess,
    band_labels,
    default_dod,
    default_payback_target_years,
    default_round_trip,
    dispatch_peak_shaving,
    ess_payback_curve,
    ess_target_curve,
    evaluate_ess,
    excess_slots_by_day,
    excess_table,
    high_rate_discharge_hours,
    light_band_mask,
    min_pcs_power_kw,
    payback_display_cap_years,
    payback_text,
    reference_targets,
    refine_ess_target,
    refine_max_widen,
    refine_targets,
    refine_window_kw,
    refine_window_ratio,
    required_discharge_hours,
    size_for_target,
    snap_spec,
    snap_step_kw,
    target_step_kw,
    viable_discharge_hours,
)
from kwise.measures.ess_cost import (
    PRICING_BANDS,
    PRICING_FORMULA,
    PRICING_QUOTED,
    CapacityBand,
    EssCostInput,
    EssCostModel,
    EssCostReference,
    EssCostReferenceError,
    EssQuote,
    EssSpecGrid,
    EssTechnologyCost,
    Feasibility,
    load_ess_cost_model,
    load_ess_cost_reference,
    load_ess_spec_grid,
    reference_table,
)
from kwise.measures.netload import NetLoad, apply_generation, with_load
from kwise.measures.power_factor import (
    PowerFactorResult,
    default_target_pct,
    evaluate_power_factor,
)
from kwise.measures.pv_cost import (
    PV_COST_BASIS_NOTE,
    PV_REFERENCE_NOTE,
    PV_UNPRICED_REASON,
    SCALE_ECONOMY_NOTE,
    PvCostInput,
    PvCostReference,
)
from kwise.measures.solar import (
    DEFAULT_MODULE_DENSITY_KWP_PER_M2,
    DEFAULT_STEPS,
    DEFAULT_USABLE_RATIO,
    CapacityVerdict,
    SolarCurve,
    SolarPoint,
    capacity_verdict,
    payback_tie_note,
    payback_tie_ratio,
    power_factor_after_pct,
    power_factor_floor_pct,
    roof_capacity_limit_kwp,
    solar_curve,
    solar_point,
    surplus_free_capacity_kwp,
    surplus_heavy_share,
    surplus_share_capacity_kwp,
    unit_generation_kw,
    with_surplus_revenue,
)
from kwise.measures.surplus import (
    APPLIED_PRICE_TAIL,
    CURTAIL_SCENARIO,
    ELIGIBILITY_NOTICE,
    EXTERNAL_SCENARIO,
    OFFSET_SCENARIO,
    OffsetMonth,
    OffsetSettlement,
    SurplusResult,
    SurplusScenario,
    applied_price_note,
    default_external_price_won_per_kwh,
    default_smp_price_won_per_kwh,
    evaluate_surplus,
    offset_carry_only_max_kw,
    offset_max_kw,
    offset_settles_cash,
    surplus_options,
)
from kwise.measures.tariff_switch import (
    OptionQuote,
    TariffSwitchResult,
    evaluate_tariff_switch,
)

__all__ = [
    "APPLIED_PRICE_TAIL",
    "AREA_EXCEEDED",
    "BELOW_MINIMUM_CONCLUSION",
    "CAPACITY_MARKS",
    "CURTAIL_SCENARIO",
    "DEFAULT_MODULE_DENSITY_KWP_PER_M2",
    "DEFAULT_STEPS",
    "DEFAULT_USABLE_RATIO",
    "DR_ADVISORY",
    "ELIGIBILITY_NOTICE",
    "EXTERNAL_SCENARIO",
    "LARGEST_SAVING",
    "MARGIN_NOTICE",
    "MARGIN_SHORT",
    "MEASURE_CATALOG",
    "NOT_VIABLE_CONCLUSION",
    "NO_SAVING",
    "OFFSET_SCENARIO",
    "PRICING_BANDS",
    "PRICING_FORMULA",
    "PRICING_QUOTED",
    "PV_COST_BASIS_NOTE",
    "PV_REFERENCE_NOTE",
    "PV_UNPRICED_REASON",
    "RECOMMENDED",
    "SCALE_ECONOMY_NOTE",
    "SELECTED_CAPACITY",
    "SHORTEST_PAYBACK",
    "SPEC_MARKS",
    "SPEC_TABLE_ROWS",
    "SURPLUS_HEAVY",
    "SURPLUS_ONSET",
    "TARGET_MISSED",
    "TIED_PAYBACK",
    "TIER_INVESTMENT",
    "TIER_LOW",
    "TIER_NONE",
    "AppliedMeasure",
    "ArbitrageValue",
    "CapacityBand",
    "CapacityVerdict",
    "Certainty",
    "ContractAdjustment",
    "ContractStatus",
    "DemandResponseResult",
    "DispatchResult",
    "EssCostInput",
    "EssCostModel",
    "EssCostReference",
    "EssCostReferenceError",
    "EssOptimum",
    "EssOptimumPoint",
    "EssQuote",
    "EssResult",
    "EssSpecGrid",
    "EssTargetCurve",
    "EssTargetPoint",
    "EssTechnologyCost",
    "Feasibility",
    "Mark",
    "MeasureKind",
    "NetLoad",
    "OffsetMonth",
    "OffsetSettlement",
    "OptionQuote",
    "PeakExcess",
    "PowerFactorResult",
    "PvCostInput",
    "PvCostReference",
    "SeasonSpread",
    "SolarCurve",
    "SolarPoint",
    "SurplusResult",
    "SurplusScenario",
    "TariffSwitchResult",
    "analyze_peak_excess",
    "annualize",
    "applied_price_note",
    "apply_generation",
    "arbitrage_value",
    "band_labels",
    "c_rate",
    "capacity_verdict",
    "default_cycles_per_day",
    "default_dod",
    "default_external_price_won_per_kwh",
    "default_payback_target_years",
    "default_round_trip",
    "default_smp_price_won_per_kwh",
    "default_target_pct",
    "dispatch_peak_shaving",
    "ess_payback_curve",
    "ess_target_curve",
    "evaluate_contract_adjustment",
    "evaluate_demand_response",
    "evaluate_ess",
    "evaluate_power_factor",
    "evaluate_surplus",
    "evaluate_tariff_switch",
    "excess_slots_by_day",
    "excess_table",
    "high_rate_discharge_hours",
    "light_band_mask",
    "load_ess_cost_model",
    "load_ess_cost_reference",
    "load_ess_spec_grid",
    "lowest_certainty",
    "mark_meaning",
    "measure_kind",
    "measure_numbers",
    "min_pcs_power_kw",
    "offset_carry_only_max_kw",
    "offset_max_kw",
    "offset_settles_cash",
    "payback_display_cap_years",
    "payback_text",
    "payback_tie_note",
    "payback_tie_ratio",
    "payback_years",
    "peak_days_by_season",
    "power_factor_after_pct",
    "power_factor_floor_pct",
    "reference_table",
    "reference_targets",
    "refine_ess_target",
    "refine_max_widen",
    "refine_targets",
    "refine_window_kw",
    "refine_window_ratio",
    "required_discharge_hours",
    "roof_capacity_limit_kwp",
    "shortfall_penalty_won",
    "size_for_target",
    "snap_spec",
    "snap_step_kw",
    "solar_curve",
    "solar_point",
    "spec_mark_meaning",
    "spec_mark_note",
    "surplus_free_capacity_kwp",
    "surplus_heavy_share",
    "surplus_options",
    "surplus_share_capacity_kwp",
    "target_step_kw",
    "unit_generation_kw",
    "viable_discharge_hours",
    "with_load",
    "with_surplus_revenue",
]
