"""개선 수단 평가 (요구사항서 7장). **7장 번호 순(7.1~7.7)이다.**

    evaluate_tariff_switch()        7.1 선택요금 전환
    evaluate_contract_adjustment()  7.2 계약전력 조정
    evaluate_demand_response()      7.3 경제성DR 참여
    evaluate_power_factor()         7.4 역률 개선
    solar_curve()                   7.5 태양광 용량 곡선
    evaluate_ess()                  7.6 ESS 목표 피크 역산
    evaluate_surplus()              7.7 잉여 활용

**모두 독립 평가다** (14세션 2절). 기준선은 언제나 현행 요금제·현행 사용량이며,
한 수단의 결과가 다른 수단의 입력이 되지 않는다. 상호작용은
:mod:`kwise.compare` 의 조합 재계산에서만 다룬다.

절감액은 언제나 재계산이다. 수단을 적용한 15분 부하를 만들어
:func:`kwise.tariff.calculate_bill` 을 다시 부른다. 그 부하를 만드는 일은
:func:`apply_generation`·:func:`with_load` 가 맡는다.
"""

from kwise.measures.arbitrage import (
    ArbitrageValue,
    SeasonSpread,
    arbitrage_value,
    c_rate,
    default_cycles_per_day,
    peak_days_by_season,
)
from kwise.measures.base import Certainty, annualize, lowest_certainty, payback_years
from kwise.measures.catalog import (
    MEASURE_CATALOG,
    TIER_INVESTMENT,
    TIER_LOW,
    TIER_NONE,
    AppliedMeasure,
    MeasureKind,
    measure_kind,
    measure_numbers,
)
from kwise.measures.contract import (
    MARGIN_NOTICE,
    ContractAdjustment,
    ContractStatus,
    evaluate_contract_adjustment,
)
from kwise.measures.demand_response import (
    DR_ADVISORY,
    DemandResponseResult,
    evaluate_demand_response,
    shortfall_penalty_won,
)
from kwise.measures.ess import (
    DispatchResult,
    EssOptimum,
    EssOptimumPoint,
    EssResult,
    EssTargetCurve,
    EssTargetPoint,
    PeakExcess,
    analyze_peak_excess,
    band_labels,
    default_dod,
    default_payback_target_years,
    default_round_trip,
    dispatch_peak_shaving,
    ess_payback_curve,
    ess_target_curve,
    evaluate_ess,
    excess_slots_by_day,
    excess_table,
    high_rate_discharge_hours,
    light_band_mask,
    refine_ess_target,
    refine_max_widen,
    refine_targets,
    refine_window_kw,
    required_discharge_hours,
    size_for_target,
)
from kwise.measures.ess_cost import (
    EssCostInput,
    EssCostModel,
    EssCostReference,
    EssCostReferenceError,
    EssQuote,
    EssTechnologyCost,
    Feasibility,
    load_ess_cost_model,
    load_ess_cost_reference,
    reference_table,
)
from kwise.measures.netload import NetLoad, apply_generation, with_load
from kwise.measures.power_factor import (
    PowerFactorResult,
    default_target_pct,
    evaluate_power_factor,
)
from kwise.measures.pv_cost import (
    PV_COST_BASIS_NOTE,
    PV_REFERENCE_NOTE,
    PV_UNPRICED_REASON,
    SCALE_ECONOMY_NOTE,
    PvCostInput,
    PvCostReference,
)
from kwise.measures.solar import (
    DEFAULT_MODULE_DENSITY_KWP_PER_M2,
    DEFAULT_STEPS,
    DEFAULT_USABLE_RATIO,
    CapacityVerdict,
    SolarCurve,
    SolarPoint,
    capacity_verdict,
    power_factor_after_pct,
    power_factor_floor_pct,
    roof_capacity_limit_kwp,
    solar_curve,
    solar_point,
    surplus_free_capacity_kwp,
    surplus_heavy_share,
    surplus_share_capacity_kwp,
    unit_generation_kw,
)
from kwise.measures.surplus import (
    ELIGIBILITY_NOTICE,
    EXTERNAL_SCENARIO,
    OFFSET_SCENARIO,
    SurplusResult,
    SurplusScenario,
    evaluate_surplus,
)
from kwise.measures.tariff_switch import (
    OptionQuote,
    TariffSwitchResult,
    evaluate_tariff_switch,
)

__all__ = [
    "DEFAULT_MODULE_DENSITY_KWP_PER_M2",
    "DEFAULT_STEPS",
    "DEFAULT_USABLE_RATIO",
    "DR_ADVISORY",
    "ELIGIBILITY_NOTICE",
    "EXTERNAL_SCENARIO",
    "MARGIN_NOTICE",
    "MEASURE_CATALOG",
    "OFFSET_SCENARIO",
    "PV_COST_BASIS_NOTE",
    "PV_REFERENCE_NOTE",
    "PV_UNPRICED_REASON",
    "SCALE_ECONOMY_NOTE",
    "TIER_INVESTMENT",
    "TIER_LOW",
    "TIER_NONE",
    "AppliedMeasure",
    "ArbitrageValue",
    "CapacityVerdict",
    "Certainty",
    "ContractAdjustment",
    "ContractStatus",
    "DemandResponseResult",
    "DispatchResult",
    "EssCostInput",
    "EssCostModel",
    "EssCostReference",
    "EssCostReferenceError",
    "EssOptimum",
    "EssOptimumPoint",
    "EssQuote",
    "EssResult",
    "EssTargetCurve",
    "EssTargetPoint",
    "EssTechnologyCost",
    "Feasibility",
    "MeasureKind",
    "NetLoad",
    "OptionQuote",
    "PeakExcess",
    "PowerFactorResult",
    "PvCostInput",
    "PvCostReference",
    "SeasonSpread",
    "SolarCurve",
    "SolarPoint",
    "SurplusResult",
    "SurplusScenario",
    "TariffSwitchResult",
    "analyze_peak_excess",
    "annualize",
    "apply_generation",
    "arbitrage_value",
    "band_labels",
    "c_rate",
    "capacity_verdict",
    "default_cycles_per_day",
    "default_dod",
    "default_payback_target_years",
    "default_round_trip",
    "default_target_pct",
    "dispatch_peak_shaving",
    "ess_payback_curve",
    "ess_target_curve",
    "evaluate_contract_adjustment",
    "evaluate_demand_response",
    "evaluate_ess",
    "evaluate_power_factor",
    "evaluate_surplus",
    "evaluate_tariff_switch",
    "excess_slots_by_day",
    "excess_table",
    "high_rate_discharge_hours",
    "light_band_mask",
    "load_ess_cost_model",
    "load_ess_cost_reference",
    "lowest_certainty",
    "measure_kind",
    "measure_numbers",
    "payback_years",
    "peak_days_by_season",
    "power_factor_after_pct",
    "power_factor_floor_pct",
    "reference_table",
    "refine_ess_target",
    "refine_max_widen",
    "refine_targets",
    "refine_window_kw",
    "required_discharge_hours",
    "roof_capacity_limit_kwp",
    "shortfall_penalty_won",
    "size_for_target",
    "solar_curve",
    "solar_point",
    "surplus_free_capacity_kwp",
    "surplus_heavy_share",
    "surplus_share_capacity_kwp",
    "unit_generation_kw",
    "with_load",
]
